config/routes.rb
Rails.application.routes.draw do
  get 'questions/index'

  # get 'questions/index'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'memory', to: 'pages#memory'
  get 'questions', to: 'questions#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/politician.rb
class Politician < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :party,  presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers

  def answers
    super.shuffle
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def memory
    @politicans = Politician.all.sample(8)
    @politicans = @politicans.shuffle

    @cards = []
    @politicans.each do |p|
      @cards << [p.picture, p.name, p.party]
      @cards << [p.picture, p.profession]
    end
    @cards.shuffle!
  end
end

app/controllers/politicians_controller.rb
class PoliticiansController < ApplicationController
  def index
  @politicians = Politician.ids.sample(8)

  end



end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Trainsparent</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>
<body>
  <%= render 'shared/navbar' %>
  <%= yield %>
  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/pages/_card.html.erb
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
  <div class="card-category">Popular</div>
  <div class="card-description">
    <h2>Le Wagon Shanghai</h2>
    <p>Very cool city, the best</p>
  </div>
  <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
  <a class="card-link" href="#" ></a>
</div>

app/views/pages/home.html.erb
<div class="background">
  <div class="col-xs-12">
    <div class="row">
      <div class="home-btn">
        <%= cl_image_tag("noun_36444_cc_icsjfq.svg", class: "circle") %>
        <%= link_to 'Quizzz Game', questions_path  %>
      </div>
    </div>
    <div class="row">
      <div class="home-btn">
        <%= cl_image_tag("noun_1003859_cc_1_1_qgicxj.svg", class: "circle") %>
        <%= link_to "Memoriezzz", memory_path %>
      </div>
    </div>
  </div>
</div>

app/views/pages/memory.html.erb
<div class="wrap">
  <div class="game">

  </div>
  <div class="modal-overlay">
    <div class="modal">
      <h2 class="winner">You win!</h2>
      <button class="restart">Play Again?</button>
    </div>
  </div>
</div>


</div>

app/views/pages/politician_info.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      </div>
    </div>
  </div>

app/views/politicians/index.html.erb
<div class="container">
  <%  @politicians.each do |politician| %>
    <%= politician %>
    <% end %>
</div>

app/views/questions/index.html.erb
<div class="questions-container">
  <div class="row">
    <% @id_number = 0 %>
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 main-wrapper">
      <div class="heading" id='<%= @id_number +=1 %>' data-next='#<%= @id_number +=1 %>'>
        <div class="col-xs-12 col-sm-6 card-heading">
          <h1>Quiz Duell For Politicians</h1>
          <p>You'll be surprised what you find here [placeholder text]</p>
          <div class='question-next-button'>
            <a href='#<%= @id_number %>'>GET STARTED</a>
          </div>
        </div>
      </div>

      <div class="card-wrapper">
      <% @questions.each do |question| %>
      <div class="heading" id='<%= @id_number %>' data-next='#<%= @id_number +=1 %>'>
        <div class="col-xs-12 col-sm-6 card-question">
          <h1 class="question"><%= question.text %></h1>
          <% shuffled = question.answers %>
          <% shuffled.each do |answer| %>
          <div class="col-xs-10 col-xs-offset-1">
              <button class="btn btn-secondary quiz-btn answer" data-correct=<%= answer.correct%>> <%= answer.text %></button>
          </div>
          <% end %>
          <div class='question-next-button disabled'>
            <a href='#<%= @id_number %>'>NEXT</a>
          </div>
          <% end %>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= cl_image_tag("Screen_Shot_2017-08-26_at_2.07.17_PM_lhw5dw.png") %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to 'Trivia Game', questions_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to 'Memory Game', memory_path, class: "navbar-wagon-item navbar-wagon-link" %>
    </div>
</div>